language: scala
scala:
  - 2.13.1
jdk:
  - openjdk8
git:
  depth: false
addons:
  sonarcloud:
    organization: "mwttg"
script:
  - sbt ++$TRAVIS_SCALA_VERSION build-complete
  - sonar-scanner -Dproject.settings=sonarcloud.properties
